apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api-keda
  labels:
    app: java-api-keda
spec:
  replicas: 0
  selector:
    matchLabels:
      app: java-api-keda
  template:
    metadata:
      labels:
        app: java-api-keda
    spec:
      containers:
        - name: java-api
          image: iesodias/java-api:latest
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: java-api-keda
spec:
  selector:
    app: java-api-keda
  ports:
    - port: 80
      targetPort: 8081
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: java-api-scaler
spec:
  scaleTargetRef:
    name: java-api-keda
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: UTC
        start: "01 17 * * *"
        end: "05 17 * * *"
        desiredReplicas: "2"